### ISSUE TITLE
attempt to retrieve old issues

### ISSUE THREAD

**Issue by afeld** [18F/notalone-backup#1]
This repository was accidentally deleted. Sounds like the Git history was recovered, but sounds like the issues may have been lost. See [the conversation in Slack](https://18f.slack.com/archives/admins-github/p1453995792000056).

@NoahKunin You [mentioned](https://18f.slack.com/archives/general-talk/p1452788239007026) using https://backhub.co/ ... would you mind:
- [ ] Confirming that the issues were backed up (or not)
- [ ] Restore the issues on this repository (if possible/easy)
- [ ] Grant more people admin access to BackHub (if others don't have it)

/cc @dhcole

**Comment by dhcole** [comment]
GitHub was able to restore the repo for us: https://github.com/18F/notalone

This repo is now obsolete. I'll let someone else delete it. I'm not touching anything again :)

**Comment by afeld** [comment]
Haha thanks for taking care of it!
